services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/18/docker
    restart: always

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    command: npm run dev
    env_file:
      - ./front/.env
    volumes:
      - ./front:/app
    ports:
      - "3001:3000"
    restart: always
    tty: true
    stdin_open: true

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    restart: always
    tty: true
    stdin_open: true
    depends_on:
      - db
volumes:
  postgres_volume:
